#!/bin/bash
#
# Submission script for the finetune_script program
#
# Comments starting with #OAR are used by the resource manager if using "oarsub -S"

# Note : quoting style of parameters matters, follow the example

#OAR -p "gpu='YES' and gpumem>30000"
#OAR -l /nodes=1/gpunum=2

#OAR -t besteffort

# The job is submitted to the default queue

nvidia-smi

python llama_inference.py

